### ISSUE TITLE
No wiki/guide on how to create a modded apk and the old one doesn't work anymore =(

### ISSUE THREAD

**Issue by Gaspa79** [expl0itr/SupercellProxy#3]
Doc reads:

"You need a modded APK file in order to capture and decrypt packets, visit our wiki and follow the instructions to mod an APK file"

But there is none =(. I found a different APK on a different repo https://github.com/jeanbmar/GL-Super-Proxy but that one doesn't work
Sorry if this is kind of abandoned, I just wanted to do some tests =)

**Comment by ToxicOverflow** [comment]
Its easy

Am 23.07.2017 4:13 nachm. schrieb "Gaspa79" <notifications@github.com>:

**Comment by Gaspa79** [comment]
Awesome =). Mind giving me a starting point? I'll take it from there.
